// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: proto/tgf.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OldestUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *ResponseUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Date string        `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *OldestUser) Reset() {
	*x = OldestUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tgf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OldestUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OldestUser) ProtoMessage() {}

func (x *OldestUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tgf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OldestUser.ProtoReflect.Descriptor instead.
func (*OldestUser) Descriptor() ([]byte, []int) {
	return file_proto_tgf_proto_rawDescGZIP(), []int{0}
}

func (x *OldestUser) GetUser() *ResponseUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *OldestUser) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ResponseUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayName string `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	ImageLink   string `protobuf:"bytes,2,opt,name=imageLink,proto3" json:"imageLink,omitempty"`
}

func (x *ResponseUser) Reset() {
	*x = ResponseUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tgf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUser) ProtoMessage() {}

func (x *ResponseUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tgf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUser.ProtoReflect.Descriptor instead.
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return file_proto_tgf_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResponseUser) GetImageLink() string {
	if x != nil {
		return x.ImageLink
	}
	return ""
}

type Streamer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Streamer        *ResponseUser `protobuf:"bytes,1,opt,name=streamer,proto3" json:"streamer,omitempty"`
	OldestUser      *OldestUser   `protobuf:"bytes,3,opt,name=oldestUser,proto3" json:"oldestUser,omitempty"`
	BroadcasterType string        `protobuf:"bytes,5,opt,name=broadcasterType,proto3" json:"broadcasterType,omitempty"`
}

func (x *Streamer) Reset() {
	*x = Streamer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tgf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Streamer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Streamer) ProtoMessage() {}

func (x *Streamer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tgf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Streamer.ProtoReflect.Descriptor instead.
func (*Streamer) Descriptor() ([]byte, []int) {
	return file_proto_tgf_proto_rawDescGZIP(), []int{2}
}

func (x *Streamer) GetStreamer() *ResponseUser {
	if x != nil {
		return x.Streamer
	}
	return nil
}

func (x *Streamer) GetOldestUser() *OldestUser {
	if x != nil {
		return x.OldestUser
	}
	return nil
}

func (x *Streamer) GetBroadcasterType() string {
	if x != nil {
		return x.BroadcasterType
	}
	return ""
}

type GetTGFRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usernames []string `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
}

func (x *GetTGFRequest) Reset() {
	*x = GetTGFRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tgf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTGFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTGFRequest) ProtoMessage() {}

func (x *GetTGFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tgf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTGFRequest.ProtoReflect.Descriptor instead.
func (*GetTGFRequest) Descriptor() ([]byte, []int) {
	return file_proto_tgf_proto_rawDescGZIP(), []int{3}
}

func (x *GetTGFRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type GetTGFResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputedUsers     []*ResponseUser `protobuf:"bytes,1,rep,name=inputedUsers,proto3" json:"inputedUsers,omitempty"`
	GeneralStreamers []*Streamer     `protobuf:"bytes,2,rep,name=generalStreamers,proto3" json:"generalStreamers,omitempty"`
}

func (x *GetTGFResponse) Reset() {
	*x = GetTGFResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tgf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTGFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTGFResponse) ProtoMessage() {}

func (x *GetTGFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tgf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTGFResponse.ProtoReflect.Descriptor instead.
func (*GetTGFResponse) Descriptor() ([]byte, []int) {
	return file_proto_tgf_proto_rawDescGZIP(), []int{4}
}

func (x *GetTGFResponse) GetInputedUsers() []*ResponseUser {
	if x != nil {
		return x.InputedUsers
	}
	return nil
}

func (x *GetTGFResponse) GetGeneralStreamers() []*Streamer {
	if x != nil {
		return x.GeneralStreamers
	}
	return nil
}

var File_proto_tgf_proto protoreflect.FileDescriptor

var file_proto_tgf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x67, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x74, 0x67, 0x66, 0x22, 0x47, 0x0a, 0x0a, 0x4f, 0x6c, 0x64, 0x65, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x67, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22,
	0x4e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x22,
	0x94, 0x01, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x08,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x67, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x0a, 0x6f,
	0x6c, 0x64, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x74, 0x67, 0x66, 0x2e, 0x4f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x0a, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f,
	0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x47, 0x46,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x47, 0x46,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x67, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x0c, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x39, 0x0a, 0x10, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x67, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x52, 0x10, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x73, 0x32, 0x54, 0x0a, 0x14, 0x54, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x73, 0x12, 0x3c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x12, 0x12, 0x2e, 0x74, 0x67, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x47, 0x46, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x74, 0x67,
	0x66, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x47, 0x46, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x6f, 0x64, 0x61, 0x6e, 0x69, 0x72, 0x75, 0x2f, 0x74, 0x67, 0x66, 0x2d, 0x67, 0x52, 0x50, 0x43,
	0x2f, 0x70, 0x6b, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tgf_proto_rawDescOnce sync.Once
	file_proto_tgf_proto_rawDescData = file_proto_tgf_proto_rawDesc
)

func file_proto_tgf_proto_rawDescGZIP() []byte {
	file_proto_tgf_proto_rawDescOnce.Do(func() {
		file_proto_tgf_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tgf_proto_rawDescData)
	})
	return file_proto_tgf_proto_rawDescData
}

var file_proto_tgf_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tgf_proto_goTypes = []interface{}{
	(*OldestUser)(nil),     // 0: tgf.OldestUser
	(*ResponseUser)(nil),   // 1: tgf.ResponseUser
	(*Streamer)(nil),       // 2: tgf.Streamer
	(*GetTGFRequest)(nil),  // 3: tgf.GetTGFRequest
	(*GetTGFResponse)(nil), // 4: tgf.GetTGFResponse
}
var file_proto_tgf_proto_depIdxs = []int32{
	1, // 0: tgf.OldestUser.user:type_name -> tgf.ResponseUser
	1, // 1: tgf.Streamer.streamer:type_name -> tgf.ResponseUser
	0, // 2: tgf.Streamer.oldestUser:type_name -> tgf.OldestUser
	1, // 3: tgf.GetTGFResponse.inputedUsers:type_name -> tgf.ResponseUser
	2, // 4: tgf.GetTGFResponse.generalStreamers:type_name -> tgf.Streamer
	3, // 5: tgf.TwitchGeneralFollows.GetGeneralFollows:input_type -> tgf.GetTGFRequest
	4, // 6: tgf.TwitchGeneralFollows.GetGeneralFollows:output_type -> tgf.GetTGFResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_tgf_proto_init() }
func file_proto_tgf_proto_init() {
	if File_proto_tgf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tgf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OldestUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tgf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tgf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Streamer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tgf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTGFRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tgf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTGFResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tgf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tgf_proto_goTypes,
		DependencyIndexes: file_proto_tgf_proto_depIdxs,
		MessageInfos:      file_proto_tgf_proto_msgTypes,
	}.Build()
	File_proto_tgf_proto = out.File
	file_proto_tgf_proto_rawDesc = nil
	file_proto_tgf_proto_goTypes = nil
	file_proto_tgf_proto_depIdxs = nil
}
