name: cicd
on: push
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: go get -d ./...
      - name: Linting
        run: go vet ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: go get -d ./...
      - name: Testing
        run: go test ./...
