name: deploy
on:
  push:
    branches:
      - 'master'



jobs:
  deploy:
    runs-on: tgf
    env:
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
    steps:
      - name: echo
        run: export TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
      - name: checkout
        uses: actions/checkout@v3
      - name: script registry
        run: chmod +x ./deploy.sh
      - name: deploy
        run: sudo ./deploy.sh