name: deploy
on:
  push:
    - 'master'

env:
  TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
  TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: ./deploy