name: deploy
on:
  push:
    branches:
      - 'master'

env:
  TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
  TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}

jobs:
  deploy:
    runs-on: tgf
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: sudo ./deploy.sh